### PR TITLE
Download Button for TUW Peer Tube

### PR DESCRIPTION
**Pull request by Fabioni**
As discussed in <https://mattermost.fsinf.at/fsinf/pl/doxrydm5sb8ptrd61qe4tyfzor>, this is a script to add a download button under the video. The button opens `https://tube1.it.tuwien.ac.at/download/videos/{{video_id}}-720.mp4`

Please "Squash and merge" the pull request.

### CODE REVIEW

**Comment by Gittenburg** [comment]
Can you share a TUpeerTube video where the download button is disabled, so that I can test your script?

**Comment by Fabioni** [comment]
> Can you share a TUpeerTube video where the download button is disabled, so that I can test your script?

https://tube1.it.tuwien.ac.at/videos/watch/3be0942c-b129-46a7-82d4-498e3caecca9

**Comment by Gittenburg** [comment]
I am wondering if it would be possible to open the actual download modal instead. I think it should be possible, the question is just how you call a method of an Angular component (`VideoWatchComponent.showDownloadModal`)  in production. `ng.probe($('my-video-watch'))` returns `null` for me.

@Otto-aa Do you have an idea?

But if we can't figure that out, that's also alright, your script does work as intended :)

**Comment by Gittenburg** [comment]
Thanks @Fabioni for your contribution! I merged the PR manually since I didn't want to squash your autologin fix together with your new script. (see https://github.com/fsinf/userscripts/commits/master for how the history looks now)

If somebody figures out how to open the download modal they can just open a new PR.

**Comment by Fabioni** [comment]
I tried to figure out how to open the modal but didn't get it. 
ng.probe doesn't work cuz angular is in production mode.

**Pull request closed without merging**
